"""
pdf_export.py
Browser-printable HTML/PDF export generation for full scan reports and
individual property one-pagers.
"""

import urllib.parse


_RADAR_LOGO_SVG = """
<svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="white" stroke-width="2.5"
     stroke-linecap="round" stroke-linejoin="round">
    <circle cx="12" cy="12" r="9" />
    <circle cx="12" cy="12" r="5" />
    <path d="M12 12 L18 6" />
    <circle cx="17" cy="7" r="1.4" fill="white" stroke="none" />
</svg>
"""


def _pdf_header_html(eyebrow_text):
    return f"""
        <div style='display:flex; align-items:center; gap:12px; margin-bottom:24px;'>
            <div style='background: linear-gradient(135deg, #2563eb, #1d4ed8); width: 44px; height: 44px;
                        border-radius: 10px; display:flex; align-items:center; justify-content:center; flex-shrink:0;'>
                {_RADAR_LOGO_SVG}
            </div>
            <div>
                <div style='font-size: 22px; font-weight: 800; color: #0f172a; line-height:1.2;'>DealRadar</div>
                <div style='font-size: 11px; color: #64748b; letter-spacing: 1px; font-weight:600;'>{eyebrow_text}</div>
            </div>
        </div>
    """


def generate_pdf_download_link(profile_name, report_markdown):
    """Converts markdown report text into a clean browser-printable string HTML asset."""
    formatted_body = report_markdown.replace("\n", "<br>").replace("### ", "<h3>").replace("## ", "<h2>").replace("# ", "<h1>")
    html_print_layout = f"""
    <html>
    <head>
        <title>DealRadar Report - {profile_name}</title>
        <style>
            body {{ font-family: 'Inter', system-ui, sans-serif; padding: 40px; color: #1e293b; line-height: 1.5; max-width: 760px; margin: 0 auto; }}
            h1, h2, h3 {{ color: #0f172a; }}
            table {{ width: 100%; border-collapse: collapse; margin: 20px 0; border-radius: 8px; overflow: hidden; }}
            th, td {{ border: 1px solid #e2e8f0; padding: 12px; text-align: left; }}
            th {{ background-color: #f8fafc; font-weight: 600; color: #334155; }}
            .dr-footer {{ margin-top: 40px; padding-top: 16px; border-top: 1px solid #e2e8f0; color: #94a3b8; font-size: 11px; }}
        </style>
    </head>
    <body>
        {_pdf_header_html(f"MARKET SCAN REPORT &middot; {profile_name}")}
        <hr style='border: 0; border-top: 1px solid #e2e8f0; margin-bottom: 24px;'>
        {formatted_body}
        <div class="dr-footer">Generated by DealRadar &middot; Simulated market data for demonstration purposes.</div>
        <script>window.onload = function() {{ window.print(); }}</script>
    </body>
    </html>
    """
    safe_uri_string = urllib.parse.quote(html_print_layout)
    return f"data:text/html;charset=utf-8,{safe_uri_string}"


def generate_single_property_pdf_link(row_item, metrics, notes=""):
    """Builds a printable one-page HTML/PDF summary for a single property,
    reusing the same browser-print approach as the full scan report export."""
    notes_html = f"<p><strong>My Notes:</strong> {notes}</p>" if notes else ""
    grade_colors = {"excellent": "#10b981", "average": "#f59e0b", "critical": "#ef4444"}
    grade_labels = {"excellent": "Outstanding Deal", "average": "Average Deal", "critical": "Negative Cash Flow"}
    grade = metrics.get("grade", "average")
    badge_color = grade_colors.get(grade, "#f59e0b")
    badge_label = grade_labels.get(grade, "Average Deal")
    html_print_layout = f"""
    <html>
    <head>
        <title>DealRadar Property - {row_item["title"]}</title>
        <style>
            body {{ font-family: 'Inter', system-ui, sans-serif; padding: 40px; color: #1e293b; line-height: 1.6; max-width: 700px; margin: 0 auto; }}
            h1, h2 {{ color: #0f172a; }}
            table {{ width: 100%; border-collapse: collapse; margin: 20px 0; }}
            th, td {{ border: 1px solid #e2e8f0; padding: 10px; text-align: left; }}
            th {{ background-color: #f8fafc; color: #334155; }}
            .dr-footer {{ margin-top: 40px; padding-top: 16px; border-top: 1px solid #e2e8f0; color: #94a3b8; font-size: 11px; }}
        </style>
    </head>
    <body>
        {_pdf_header_html("SINGLE PROPERTY REPORT")}
        <hr style='border: 0; border-top: 1px solid #e2e8f0; margin-bottom: 24px;'>
        <div style='display:flex; align-items:center; justify-content:space-between; gap:16px; flex-wrap:wrap;'>
            <h1 style='margin:0;'>{row_item['title']}</h1>
            <span style='background:{badge_color}22; color:{badge_color}; font-weight:700; font-size:12px;
                         padding:5px 12px; border-radius:999px; white-space:nowrap;'>{badge_label}</span>
        </div>
        <p style='color:#64748b;'>{row_item.get('address', '')}</p>
        <table>
            <tr><th>Price</th><td>${row_item['price']:,.0f}</td></tr>
            <tr><th>Beds / Baths</th><td>{row_item.get('beds', '-')} bd / {row_item.get('baths', '-')} ba</td></tr>
            <tr><th>Cap Rate</th><td>{metrics['cap_rate']:.2f}%</td></tr>
            <tr><th>Cash-on-Cash Return</th><td>{metrics['coc']:.2f}%</td></tr>
            <tr><th>Annual NOI</th><td>${metrics['noi']:,.2f}</td></tr>
            <tr><th>Annual Cash Flow</th><td>${metrics['cashflow']:,.2f}</td></tr>
            <tr><th>Maximum Allowable Offer</th><td>${metrics['mao']:,.2f}</td></tr>
        </table>
        {notes_html}
        <div class="dr-footer">Generated by DealRadar &middot; Simulated market data for demonstration purposes.</div>
        <script>window.onload = function() {{ window.print(); }}</script>
    </body>
    </html>
    """
    safe_uri_string = urllib.parse.quote(html_print_layout)
    return f"data:text/html;charset=utf-8,{safe_uri_string}"